[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=40.8.0", "wheel"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "readmeai"
version = "0.2.2"
description = "🚀 Generate awesome README.md files from the terminal, powered by OpenAI's GPT language model APIs 💫"
authors = ["Eli <0x.eli.64s@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/eli64s/readme-ai"
documentation = "https://github.com/eli64s/readme-ai/blob/main/README.md"
keywords = [
  "readme",
  "python-cli",
  "readme-template",
  "readme-md",
  "awesome-readme",
  "readme-generator",
  "gpt-3",
  "openai-api",
  "automated-readme",
  "auto-readme",
  "gpt-4",
  "llms",
  "openai-python",
  "chatgpt-python",
  "gpt-35-turbo",
  "gpt-4-api",
  "openai-cli",
  "llm-prompting",
  "llm-agent",
]

[tool.poetry.dev-dependencies]
black = "*"
flake8 = "*"
isort = "*"
pytest = "*"
pytest-cov = "*"
pre-commit = "*"
ruff = "*"

[tool.poetry.dependencies]
python = "^3.8.1"
colorlog = "^6.7.0"
cachetools = "^5.3.1"
gitpython = "^3.1.31"
httpx = "^0.24.1"
h2 = "^4.1.0"
openai = "^0.27.8"
pyyaml = "^6.0"
responses = "^0.23.1"
tabulate = "^0.9.0"
tenacity = "^8.2.2"
tiktoken = "^0.4.0"
toml = "^0.10.2"
pydantic = "^1.10.9"
click = "^8.1.6"

[tool.poetry.scripts]
readmeai = "readmeai.main:cli"

[tool.ruff]
line-length = 88
target-version = "py39"
extend-select = [
  "I", # isort
  "N", # pep8-naming
  "UP", # pyupgrade
  "RUF", # ruff
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "PTH", # flake8-use-pathlib
  "SIM", # flake8-simplify
  "TID", # flake8-tidy-imports
]

[tool.ruff.isort]
force-sort-within-sections = true
split-on-trailing-comma = false

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "--strict-markers --disable-pytest-warnings"

[tool.coverage.run]
omit = ["tests/*", "*/__init__.py"]

[tool.setuptools.package-data]
"readmeai.conf" = ["**/*.toml"]
